/* Generated automatically by the program `gencodes'
from the machine description file `md'.  */

#ifndef MAX_INSN_CODE

enum insn_code {
  CODE_FOR_cmpsi = 0,
  CODE_FOR_cmpsf = 2,
  CODE_FOR_cmpdf = 3,
  CODE_FOR_jump = 4,
  CODE_FOR_tablejump = 5,
  CODE_FOR_beq = 6,
  CODE_FOR_bne = 8,
  CODE_FOR_blt = 10,
  CODE_FOR_bge = 12,
  CODE_FOR_bgt = 14,
  CODE_FOR_ble = 16,
  CODE_FOR_bltu = 18,
  CODE_FOR_bgeu = 20,
  CODE_FOR_bgtu = 22,
  CODE_FOR_bleu = 24,
  CODE_FOR_movsi = 26,
  CODE_FOR_movhi = 27,
  CODE_FOR_movqi = 28,
  CODE_FOR_movdi = 29,
  CODE_FOR_movsf = 30,
  CODE_FOR_movdf = 31,
  CODE_FOR_truncsiqi2 = 32,
  CODE_FOR_truncsihi2 = 33,
  CODE_FOR_zero_extendhisi2 = 34,
  CODE_FOR_zero_extendqisi2 = 35,
  CODE_FOR_zero_extendqihi2 = 36,
  CODE_FOR_extendqihi2 = 37,
  CODE_FOR_extendhisi2 = 38,
  CODE_FOR_extendqisi2 = 39,
  CODE_FOR_extendsfdf2 = 40,
  CODE_FOR_truncdfsf2 = 41,
  CODE_FOR_addsi3 = 43,
  CODE_FOR_subsi3 = 45,
  CODE_FOR_mulsi3 = 46,
  CODE_FOR_divsi3 = 47,
  CODE_FOR_udivsi3 = 48,
  CODE_FOR_modsi3 = 49,
  CODE_FOR_umodsi3 = 50,
  CODE_FOR_negsi2 = 51,
  CODE_FOR_andsi3 = 52,
  CODE_FOR_iorsi3 = 53,
  CODE_FOR_xorsi3 = 54,
  CODE_FOR_one_cmplsi2 = 55,
  CODE_FOR_ashlsi3 = 56,
  CODE_FOR_ashrsi3 = 57,
  CODE_FOR_lshrsi3 = 58,
  CODE_FOR_addsf3 = 59,
  CODE_FOR_subsf3 = 60,
  CODE_FOR_mulsf3 = 61,
  CODE_FOR_divsf3 = 62,
  CODE_FOR_negsf2 = 63,
  CODE_FOR_abssf2 = 64,
  CODE_FOR_adddf3 = 65,
  CODE_FOR_subdf3 = 66,
  CODE_FOR_muldf3 = 67,
  CODE_FOR_divdf3 = 68,
  CODE_FOR_negdf2 = 69,
  CODE_FOR_absdf2 = 70,
  CODE_FOR_floatsisf2 = 71,
  CODE_FOR_floatsidf2 = 72,
  CODE_FOR_fix_truncsfsi2 = 73,
  CODE_FOR_fix_truncdfsi2 = 74,
  CODE_FOR_call = 75,
  CODE_FOR_call_value = 76,
  CODE_FOR_nop = 77,
  CODE_FOR_indirect_jump = 78,
  CODE_FOR_nothing };

#define MAX_INSN_CODE ((int) CODE_FOR_nothing)
#endif /* MAX_INSN_CODE */
